# Generated by Django 6.0.7 on 2026-09-01 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('batch_number', models.CharField(max_length=100)),
                ('manufacturing_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('number_of_units', models.PositiveIntegerField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='medicine_master.medicine')),
            ],
            options={
                'db_table': 'medicine_inventory',
            },
        ),
    ]
