# Generated by Django 6.0.7 on 2026-09-02 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_laborder_medicineprescription_delete_prescription'),
        ('medicine_master', '0001_initial'),
        ('pharmacy', '0001_initial'),
        ('receptionist', '0003_consultationbill'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_bills', to='receptionist.patient')),
            ],
            options={
                'db_table': 'pharmacy_bill',
            },
        ),
        migrations.CreateModel(
            name='PharmacyBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicine_master.medicine')),
                ('pharmacy_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.pharmacybill')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_items', to='doctor.medicineprescription')),
            ],
            options={
                'db_table': 'pharmacy_bill_item',
            },
        ),
    ]
