# Generated by Django 6.0.7 on 2026-09-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_pharmacybill_pharmacybillitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineinventory',
            name='max_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicineinventory',
            name='min_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
