# Generated by Django 6.1 on 2026-09-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='strength_unit',
            field=models.CharField(blank=True, choices=[('MG', 'mg'), ('G', 'g'), ('MCG', 'mcg'), ('ML', 'ml'), ('L', 'L'), ('MG/ML', 'mg/ml'), ('MCG/ML', 'mcg/ml'), ('IU', 'IU'), ('%', '%')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dosage_form',
            field=models.CharField(blank=True, choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('SUSPENSION', 'Suspension'), ('OINTMENT', 'Ointment'), ('CREAM', 'Cream'), ('GEL', 'Gel'), ('DROPS', 'Drops'), ('INJECTION', 'Injection'), ('POWDER', 'Powder')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='strength',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
