# Generated by Django 6.1 on 2026-09-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_master', '0002_medicine_strength_unit_alter_medicine_dosage_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='strength',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
