# Generated by Django 6.1 on 2026-09-02 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_laborder_medicineprescription_delete_prescription'),
        ('medicine_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineprescription',
            name='medicine_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='medicineprescription',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicine_prescriptions', to='medicine_master.medicine'),
        ),
    ]
