# Generated by Django 6.1 on 2026-09-02 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_medicineprescription_medicine_name_and_more'),
        ('lab_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='lab_test_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='lab_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='lab_master.labtest'),
        ),
    ]
