# Generated by Django 6.1 on 2026-09-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_laborder_lab_test_name_alter_laborder_lab_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineprescription',
            name='dosage',
        ),
        migrations.AddField(
            model_name='medicineprescription',
            name='duration_unit',
            field=models.CharField(choices=[('DAYS', 'Days'), ('WEEKS', 'Weeks'), ('MONTHS', 'Months')], default='DAYS', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicineprescription',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicineprescription',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='medicineprescription',
            name='frequency',
            field=models.CharField(max_length=20),
        ),
    ]
